git:
  log:
    showGraph: 'always'
  branchLogCmd: 'git log --graph --color=always --pretty="%C(auto)%h%x09%C(82)%aN%x09%Creset%s [%C(6)%cr%C(reset)] %C(auto)%d" {{branchName}} --'
  pagers:
    - pager: delta --dark --paging=never --line-numbers
      colorArg: always
  allBranchesLogCmds:
    - git log --graph --all --color=always --pretty="%C(auto)%h%x09%C(82)%aN%x09%Creset%s [%C(6)%cr%C(reset)] %C(auto)%d"
